site_name: PHYS3080 Distance Ladder Project
site_url: https://astrouq.github.io/ladder/
site_author: Ryan White, Benjamin Pope
theme:
  name: "material"
  logo: MiscGithubImages/SBa.jpg
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
# extra:
#     social:
#         - icon: fontawesome/brands/github
#           link: https://github.com/astrouq
copyright: Copyright &copy; 2023 Ryan White, Benjamin Pope

repo_url: https://github.com/astrouq/ladder
edit_uri: ""
nav: 
    - 'Home': index.md
    - Learning Python: software.md
    - 'Datasets': Datasets.md
    - 'Tutorials':
        - Introduction: Tutorials/introduction.md
        - 'Un-Cubemapping Data': Tutorials/Tutorials/Un-Cubemapping Data.ipynb
        - 'Fitting a Line to Data': Tutorials/
        # - Uncertainties in Data: Tutorials/Uncertainties.md
        # - 'Useful Formulae': Tutorials/UsefulFormulae.md
    - 'Tutorials':
        - Introduction: Tutorials/Tutorials/introduction.md
        - HR Diagrams: notebooks/hr_diagram.ipynb
        - Periodograms: notebooks/lombscargle_example.ipynb
        # - 'Local Galaxy, Finding Variable Periods': Tutorials/Tutorials/Local Universe.ipynb
        # - 'Plotting a HR Diagram and Blackbody Curves': Tutorials/Tutorials/HR_Temp.ipynb
        - Identifying Galaxies: Tutorials/Tutorials/GalaxyFinding.ipynb
        # - Rotation Curves: Tutorials/Tutorials/Rotation Curves.ipynb
        # - Distance Ladder I: Tutorials/Tutorials/Distance Ladder I; Resolved Galaxies.ipynb
        # - Distance Ladder II: Tutorials/Tutorials/Distance Ladder II; X-Ray Flashes and Distant Galaxies.ipynb
    - 'About':
        - About: About.md
        # - GitHub Readme: GitHub README.md
        # - License: License.md
    
plugins:
    - search
    - mkdocs-jupyter:
        include_source: true
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "numpy"
                rendering:
                    show_source: false
        custom_templates: templates

markdown_extensions:
    - meta
    - pymdownx.arithmatex:
        generic: true
    - mdx_math  #https://stackoverflow.com/questions/27882261/mkdocs-and-mathjax <- source!
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js