site_name: PHYS3080 Distance Ladder Project
site_url: https://astrouq.github.io/ladder/
site_author: Ryan White, Benjamin Pope
theme:
  name: "material"
  logo: MiscGithubImages/SBa.jpg
  palette:
    primary: deep purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
copyright: Copyright &copy; 2023 Ryan White, Benjamin Pope

repo_url: https://github.com/astrouq/ladder
edit_uri: ""
nav: 
    - 'Home': index.md
    - Learning Python: tutorials/software.md
    - 'Datasets': 
        - Datasets: datasets.md
        - Data Structure: data.md
    - 'Tutorials':
        - Introduction: tutorials/introduction.md
        - 'Un-Cubemapping Data': tutorials/uncubemapping.ipynb
        - 'Fitting a Line to Data': tutorials/fitting-a-line.ipynb
        - HR Diagrams: tutorials/hr_diagram.ipynb
        - Periodograms: tutorials/lombscargle_example.ipynb
    - 'About':
        - About: About.md
    
plugins:
    - search
    - mkdocs-jupyter:
        include_source: true
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "numpy"
                rendering:
                    show_source: false
        custom_templates: templates

markdown_extensions:
    - meta
    - pymdownx.arithmatex:
        generic: true
    - mdx_math  #https://stackoverflow.com/questions/27882261/mkdocs-and-mathjax <- source!
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js