site_name: Simulated Universe
site_url: https://ryanwhite1.github.io/Simulated-Universe/
site_author: Ryan White
theme:
  name: "material"
  logo: MiscGithubImages/SBc.jpg
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/ryanwhite1
copyright: Copyright &copy; 2022 Ryan White

repo_url: https://github.com/ryanwhite1/Simulated-Universe
#repo_name: ryanwhite1/Simulated-Universe
nav: 
    - 'Home': index.md
    - 'Datasets': Datasets.md
    - 'Analysing Data':
        - Introduction: Analysing Data/introduction.md
        - Uncertainties in Data: Analysing Data/Uncertainties.md
        - 'Walkthrough (Spoilers!)':
            - Introduction: Analysing Data/Walkthrough/introduction.md
            - Local Universe: Analysing Data/Walkthrough/Local Universe.ipynb
    - 'About':
        - About: About.md
        - GitHub Readme: GitHub README.md
        - License: License.md
    
plugins:
    - search
    - mkdocs-jupyter
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "numpy"
                rendering:
                    show_source: false
        custom_templates: templates

markdown_extensions:
    - meta
    - pymdownx.arithmatex:
        generic: true
    - mdx_math  #https://stackoverflow.com/questions/27882261/mkdocs-and-mathjax <- source!
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js