site_name: PHYS3080 Distance Ladder Project
site_url: https://astrouq.github.io/ladder/
site_author: Ryan White, Benjamin Pope
theme:
  name: "material"
  logo: MiscGithubImages/SBa.jpg
  palette:
    primary: black
    accent: black
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/astrouq
copyright: Copyright &copy; 2023 Ryan White, Benjamin Pope

repo_url: https://github.com/astrouq/ladder
edit_uri: ""
nav: 
    - 'Home': index.md
    - 'Datasets': Datasets.md
    - 'Analysing Data':
        - Introduction: Analysing Data/introduction.md
        - Uncertainties in Data: Analysing Data/Uncertainties.md
        - 'Useful Formulae': Analysing Data/UsefulFormulae.md
    - 'Walkthrough':
        - Introduction: Analysing Data/Walkthrough/introduction.md
        - 'Un-Cubemapping Data': Analysing Data/Walkthrough/Un-Cubemapping Data.ipynb
        - 'Local Galaxy, Finding Variable Periods': Analysing Data/Walkthrough/Local Universe.ipynb
        - 'Plotting a HR Diagram and Blackbody Curves': Analysing Data/Walkthrough/HR_Temp.ipynb
        - Identifying Galaxies: Analysing Data/Walkthrough/GalaxyFinding.ipynb
        - Rotation Curves: Analysing Data/Walkthrough/Rotation Curves.ipynb
        - Distance Ladder I: Analysing Data/Walkthrough/Distance Ladder I; Resolved Galaxies.ipynb
        - Distance Ladder II: Analysing Data/Walkthrough/Distance Ladder II; X-Ray Flashes and Distant Galaxies.ipynb
    - 'About':
        - About: About.md
        - GitHub Readme: GitHub README.md
        - License: License.md
    
plugins:
    - search
    - mkdocs-jupyter:
        include_source: true
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "numpy"
                rendering:
                    show_source: false
        custom_templates: templates

markdown_extensions:
    - meta
    - pymdownx.arithmatex:
        generic: true
    - mdx_math  #https://stackoverflow.com/questions/27882261/mkdocs-and-mathjax <- source!
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js