site_name: Distance Ladder Simulated Universe
theme:
  name: bootstrap4
  palette:
    primary: black

nav: 
    - 'Home': 'index.md'
    - 'Analysing Data':
        - h: 'Analysing Data/h.md'
    - 'About':
        - About: 'About.md'
        - License: 'License.md'
    
plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                selection:
                    docstring_style: "numpy"
                rendering:
                    show_source: false
        custom_templates: templates